### ISSUE TITLE
off the shelf VideoBert model

### ISSUE THREAD

**Issue by EeyoreLee** [zhaogangthu/multi-task-bert#1]
I saw you have used the videobert(pai-videobert-base-zh). Would you release it ? I can't find off-the-shelf videobert model anywhere . T_T

**Comment by zhaogangthu** [comment]
> pai-videobert-base-zh

**Comment by zhaogangthu** [comment]
> I saw you have used the videobert(pai-videobert-base-zh). Would you release it ? I can't find off-the-shelf videobert model anywhere . T_T

Sorry, I didn't use pai-videobert-base-zh. It cannot be downloaded automatically by easytransfer?

**Comment by EeyoreLee** [comment]
> > I saw you have used the videobert(pai-videobert-base-zh). Would you release it ? I can't find off-the-shelf videobert model anywhere . T_T
> 
> Sorry, I didn't use pai-videobert-base-zh. It cannot be downloaded automatically by easytransfer?

Thanks for your reply.
I don't know how to get it(pai-videobert-base-zh) which seems that  it does not appear to be officially disclosed.  
If possible, could you attach a link to the model.
